/*
 * @Author: your name
 * @Date: 2020-01-07 20:16:20
 * @LastEditTime : 2020-01-19 15:17:59
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /cloud-music/src/application/Player/store/reducer.js
 */
import * as actionTypes from './constants';
import { fromJS } from 'immutable';
import { playMode } from '../../../api/config';

const defaultState = fromJS({
    fullScreen: false,// 播放器是否为全屏模式
    playing: false, // 当前歌曲是否播放
    sequencePlayList: [
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12054456,
                    "name":"董又霖",
                    "alia":[
                        "Jeffrey"
                    ]
                },
                {
                    "id":12118230,
                    "name":"钱正昊"
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                },
                {
                    "id":12493781,
                    "name":"Lil Ghost小鬼",
                    "alia":[
                        "王琳凯"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13056440,
                    "name":"陈立农"
                },
                {
                    "id":13056442,
                    "name":"范丞丞"
                },
                {
                    "id":13056454,
                    "name":"灵超"
                },
                {
                    "id":13057497,
                    "name":"黄明昊 (Justin)"
                },
                {
                    "id":13057511,
                    "name":"郑艺彬"
                },
                {
                    "id":13057513,
                    "name":"朱正廷"
                },
                {
                    "id":13057676,
                    "name":"李希侃"
                },
                {
                    "id":13058487,
                    "name":"毕雯珺"
                },
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13058498,
                    "name":"林彦俊"
                },
                {
                    "id":13058502,
                    "name":"王子异"
                },
                {
                    "id":13058503,
                    "name":"尤长靖"
                },
                {
                    "id":13059447,
                    "name":"林超泽"
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":3,
            "fee":0,
            "djId":0,
            "v":11,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":224430,
            "h":{
                "br":320000,
                "fid":0,
                "size":8979897,
                "vd":-6800
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3591985,
                "vd":-3100
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5387955,
                "vd":-4300
            },
            "cd":"01",
            "name":"Forever (Live)",
            "id":550136152,
            "privilege":{
                "id":550136152,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13056440,
                    "name":"陈立农"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                },
                {
                    "id":13056442,
                    "name":"范丞丞"
                },
                {
                    "id":12118230,
                    "name":"钱正昊"
                },
                {
                    "id":13058502,
                    "name":"王子异"
                },
                {
                    "id":13057513,
                    "name":"朱正廷"
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":2,
            "fee":0,
            "djId":0,
            "v":10,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":190914,
            "h":{
                "br":320000,
                "fid":0,
                "size":7639293,
                "vd":-22900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3055743,
                "vd":-19400
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4583593,
                "vd":-20500
            },
            "cd":"01",
            "name":"Mack Daddy (Live)",
            "id":550138132,
            "privilege":{
                "id":550138132,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13057511,
                    "name":"郑艺彬"
                },
                {
                    "id":12493781,
                    "name":"Lil Ghost小鬼",
                    "alia":[
                        "王琳凯"
                    ]
                },
                {
                    "id":13057676,
                    "name":"李希侃"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":5,
            "fee":0,
            "djId":0,
            "v":66,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":203545,
            "h":{
                "br":320000,
                "fid":0,
                "size":8143978,
                "vd":-25900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3257617,
                "vd":-22000
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4886404,
                "vd":-23400
            },
            "cd":"05",
            "name":"听听我说的吧 (Live)",
            "id":545592271,
            "privilege":{
                "id":545592271,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12097022,
                    "name":"程潇",
                    "tns":[
                        "성소 Of 宇宙少女"
                    ]
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13057497,
                    "name":"黄明昊 (Justin)"
                },
                {
                    "id":13057501,
                    "name":"罗正"
                },
                {
                    "id":13058489,
                    "name":"丁泽仁"
                },
                {
                    "id":13058506,
                    "name":"周彦辰"
                },
                {
                    "id":13059435,
                    "name":"何东东"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":1,
            "fee":0,
            "djId":0,
            "v":32,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":163420,
            "h":{
                "br":320000,
                "fid":0,
                "size":6539015,
                "vd":-16300
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2615632,
                "vd":-12400
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":3923426,
                "vd":-13800
            },
            "cd":"06",
            "name":"24K Magic Remix Havana (Live)",
            "id":548651095,
            "privilege":{
                "id":548651095,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":1083118,
                    "name":"王嘉尔",
                    "tns":[
                        "Jackson of GOT7"
                    ],
                    "alia":[
                        "Jackson"
                    ]
                }
            ],
            "al":{
                "id":79834543,
                "name":"Another (Feat. 王嘉尔)",
                "picUrl":"https://p2.music.126.net/u9wmbngdd1aqbbQgRkR9Ng==/109951164154625917.jpg",
                "pic_str":"109951164154625917",
                "pic":109951164154625920
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":3,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":95,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":236360,
            "h":{
                "br":320000,
                "fid":0,
                "size":9457005,
                "vd":-60921
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3782829,
                "vd":-56913
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5674221,
                "vd":-58428
            },
            "cd":"01",
            "name":"Another (Feat. 王嘉尔)",
            "id":1372370576,
            "privilege":{
                "id":1372370576,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":0,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12054456,
                    "name":"董又霖",
                    "alia":[
                        "Jeffrey"
                    ]
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":13056454,
                    "name":"灵超"
                },
                {
                    "id":13056463,
                    "name":"王梓豪"
                },
                {
                    "id":13059438,
                    "name":"伽里"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":14,
            "fee":0,
            "djId":0,
            "v":101,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":95,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":228623,
            "h":{
                "br":320000,
                "fid":0,
                "size":9147080,
                "vd":0
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3658858,
                "vd":-2
            },
            "alia":[
                "原唱：CNBLUE"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5488266,
                "vd":-2
            },
            "cd":"01",
            "name":"Can't Stop (B组现场版)",
            "id":534541397,
            "privilege":{
                "id":534541397,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12787978,
                    "name":"李让同学"
                },
                {
                    "id":13056451,
                    "name":"靖佩瑶"
                },
                {
                    "id":13059432,
                    "name":"董岩磊"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":3,
            "fee":0,
            "djId":0,
            "v":86,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":90,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":157856,
            "h":{
                "br":320000,
                "fid":0,
                "size":6321676,
                "vd":-22000
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2528697,
                "vd":-18000
            },
            "alia":[
                "原唱：DJ Snake & Lil Jon"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":3793023,
                "vd":-19500
            },
            "cd":"01",
            "name":"Turn Down for What (Live)",
            "id":544000402,
            "privilege":{
                "id":544000402,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":320000,
                "dl":320000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":320000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12274111,
                    "name":"任嘉伦"
                },
                {
                    "id":6076,
                    "name":"俞灏明"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":29817313,
                    "name":"费启鸣"
                }
            ],
            "al":{
                "id":72070002,
                "name":"童话梦想家",
                "picUrl":"https://p2.music.126.net/-kLC8gL27b236EWFM5uVSA==/109951163446549794.jpg",
                "pic_str":"109951163446549794",
                "pic":109951163446549800
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":6,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":90,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1416500,
            "cf":"",
            "dt":190666,
            "h":{
                "br":320000,
                "fid":0,
                "size":7628844,
                "vd":-20900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3051564,
                "vd":-16800
            },
            "alia":[
                "节目《超能幼稚园》片尾曲"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4577324,
                "vd":-18300
            },
            "cd":"1",
            "name":"童话梦想家",
            "id":1299550218,
            "privilege":{
                "id":1299550218,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":4,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12274111,
                    "name":"任嘉伦"
                },
                {
                    "id":6076,
                    "name":"俞灏明"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":29817313,
                    "name":"费启鸣"
                }
            ],
            "al":{
                "id":72015226,
                "name":"我只是个孩子",
                "picUrl":"https://p2.music.126.net/agkP-pvcGfBT0OWIkJdFmQ==/109951163437872756.jpg",
                "pic_str":"109951163437872756",
                "pic":109951163437872750
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":7,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":85,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1416500,
            "cf":"",
            "dt":227624,
            "h":{
                "br":320000,
                "fid":0,
                "size":9107374,
                "vd":-19900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3642976,
                "vd":-15800
            },
            "alia":[
                "节目《超能幼稚园》主题曲"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5464442,
                "vd":-17400
            },
            "cd":"1",
            "name":"我只是个孩子",
            "id":1298130518,
            "privilege":{
                "id":1298130518,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":4,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":1142042,
                    "name":"徐梦圆"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                }
            ],
            "al":{
                "id":36633094,
                "name":"KINGSMAN",
                "picUrl":"https://p2.music.126.net/ldh6m60z5UuxlK5LVnifDw==/109951163046793719.jpg",
                "pic_str":"109951163046793719",
                "pic":109951163046793710
            },
            "st":0,
            "no":0,
            "fee":0,
            "djId":0,
            "v":8,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":80,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":462012,
            "cf":"",
            "dt":228011,
            "h":{
                "br":320000,
                "fid":0,
                "size":9123048,
                "vd":-28599
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3649245,
                "vd":-25200
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5473846,
                "vd":-26199
            },
            "cd":"01",
            "name":"KINGSMAN",
            "id":514054561,
            "privilege":{
                "id":514054561,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                }
            ],
            "al":{
                "id":74210688,
                "name":"Show Me",
                "picUrl":"https://p2.music.126.net/9xoTMqmU6nlqvY6WRhJYbw==/109951163641264944.jpg",
                "pic_str":"109951163641264944",
                "pic":109951163641264940
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":5,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":80,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":201609,
            "h":{
                "br":320000,
                "fid":0,
                "size":8066656,
                "vd":-2
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3226688,
                "vd":-2
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4840011,
                "vd":-2
            },
            "cd":"01",
            "name":"Show Me",
            "id":1322299910,
            "privilege":{
                "id":1322299910,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                }
            ],
            "al":{
                "id":72192132,
                "name":"绯",
                "picUrl":"https://p2.music.126.net/ePFZSPhvpFYTqxGcL0jcLA==/109951163446908880.jpg",
                "pic_str":"109951163446908880",
                "pic":109951163446908880
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":10,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":70,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":166907,
            "h":{
                "br":320000,
                "fid":0,
                "size":6679031,
                "vd":-2
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2671639,
                "vd":-2
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4007436,
                "vd":-2
            },
            "cd":"1",
            "name":"绯",
            "id":1299873774,
            "privilege":{
                "id":1299873774,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                }
            ],
            "al":{
                "id":84388544,
                "name":"红旗飘飘",
                "picUrl":"https://p2.music.126.net/3ro4RFV2FaPnk_p8MBTurw==/109951164582603045.jpg",
                "pic_str":"109951164582603045",
                "pic":109951164582603040
            },
            "st":1,
            "no":0,
            "fee":8,
            "djId":0,
            "v":2,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":70,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":1416582,
            "cf":"",
            "dt":247687,
            "h":{
                "br":320000,
                "fid":0,
                "size":9909856,
                "vd":-48071
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3963968,
                "vd":-43826
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5945931,
                "vd":-45470
            },
            "cd":"01",
            "name":"红旗飘飘",
            "id":1412241777,
            "privilege":{
                "id":1412241777,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":64,
                "preSell":false
            }
        }
    ], // 顺序列表 (因为之后会有随机模式，列表会乱序，因从拿这个保存顺序列表)
    playList: [
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12054456,
                    "name":"董又霖",
                    "alia":[
                        "Jeffrey"
                    ]
                },
                {
                    "id":12118230,
                    "name":"钱正昊"
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                },
                {
                    "id":12493781,
                    "name":"Lil Ghost小鬼",
                    "alia":[
                        "王琳凯"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13056440,
                    "name":"陈立农"
                },
                {
                    "id":13056442,
                    "name":"范丞丞"
                },
                {
                    "id":13056454,
                    "name":"灵超"
                },
                {
                    "id":13057497,
                    "name":"黄明昊 (Justin)"
                },
                {
                    "id":13057511,
                    "name":"郑艺彬"
                },
                {
                    "id":13057513,
                    "name":"朱正廷"
                },
                {
                    "id":13057676,
                    "name":"李希侃"
                },
                {
                    "id":13058487,
                    "name":"毕雯珺"
                },
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13058498,
                    "name":"林彦俊"
                },
                {
                    "id":13058502,
                    "name":"王子异"
                },
                {
                    "id":13058503,
                    "name":"尤长靖"
                },
                {
                    "id":13059447,
                    "name":"林超泽"
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":3,
            "fee":0,
            "djId":0,
            "v":11,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":224430,
            "h":{
                "br":320000,
                "fid":0,
                "size":8979897,
                "vd":-6800
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3591985,
                "vd":-3100
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5387955,
                "vd":-4300
            },
            "cd":"01",
            "name":"Forever (Live)",
            "id":550136152,
            "privilege":{
                "id":550136152,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13056440,
                    "name":"陈立农"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                },
                {
                    "id":13056442,
                    "name":"范丞丞"
                },
                {
                    "id":12118230,
                    "name":"钱正昊"
                },
                {
                    "id":13058502,
                    "name":"王子异"
                },
                {
                    "id":13057513,
                    "name":"朱正廷"
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":2,
            "fee":0,
            "djId":0,
            "v":10,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":190914,
            "h":{
                "br":320000,
                "fid":0,
                "size":7639293,
                "vd":-22900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3055743,
                "vd":-19400
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4583593,
                "vd":-20500
            },
            "cd":"01",
            "name":"Mack Daddy (Live)",
            "id":550138132,
            "privilege":{
                "id":550138132,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12932368,
                    "name":"蔡徐坤",
                    "tns":[
                        "KUN"
                    ]
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13058488,
                    "name":"卜凡"
                },
                {
                    "id":13057511,
                    "name":"郑艺彬"
                },
                {
                    "id":12493781,
                    "name":"Lil Ghost小鬼",
                    "alia":[
                        "王琳凯"
                    ]
                },
                {
                    "id":13057676,
                    "name":"李希侃"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":5,
            "fee":0,
            "djId":0,
            "v":66,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":203545,
            "h":{
                "br":320000,
                "fid":0,
                "size":8143978,
                "vd":-25900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3257617,
                "vd":-22000
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4886404,
                "vd":-23400
            },
            "cd":"05",
            "name":"听听我说的吧 (Live)",
            "id":545592271,
            "privilege":{
                "id":545592271,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12097022,
                    "name":"程潇",
                    "tns":[
                        "성소 Of 宇宙少女"
                    ]
                },
                {
                    "id":12120150,
                    "name":"朱星杰",
                    "alia":[
                        "J.Zen"
                    ]
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13057497,
                    "name":"黄明昊 (Justin)"
                },
                {
                    "id":13057501,
                    "name":"罗正"
                },
                {
                    "id":13058489,
                    "name":"丁泽仁"
                },
                {
                    "id":13058506,
                    "name":"周彦辰"
                },
                {
                    "id":13059435,
                    "name":"何东东"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":1,
            "fee":0,
            "djId":0,
            "v":32,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":100,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":163420,
            "h":{
                "br":320000,
                "fid":0,
                "size":6539015,
                "vd":-16300
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2615632,
                "vd":-12400
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":3923426,
                "vd":-13800
            },
            "cd":"06",
            "name":"24K Magic Remix Havana (Live)",
            "id":548651095,
            "privilege":{
                "id":548651095,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":1083118,
                    "name":"王嘉尔",
                    "tns":[
                        "Jackson of GOT7"
                    ],
                    "alia":[
                        "Jackson"
                    ]
                }
            ],
            "al":{
                "id":79834543,
                "name":"Another (Feat. 王嘉尔)",
                "picUrl":"https://p2.music.126.net/u9wmbngdd1aqbbQgRkR9Ng==/109951164154625917.jpg",
                "pic_str":"109951164154625917",
                "pic":109951164154625920
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":3,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":95,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":236360,
            "h":{
                "br":320000,
                "fid":0,
                "size":9457005,
                "vd":-60921
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3782829,
                "vd":-56913
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5674221,
                "vd":-58428
            },
            "cd":"01",
            "name":"Another (Feat. 王嘉尔)",
            "id":1372370576,
            "privilege":{
                "id":1372370576,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":0,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12054456,
                    "name":"董又霖",
                    "alia":[
                        "Jeffrey"
                    ]
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":13056454,
                    "name":"灵超"
                },
                {
                    "id":13056463,
                    "name":"王梓豪"
                },
                {
                    "id":13059438,
                    "name":"伽里"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":13059454,
                    "name":"徐圣恩",
                    "alia":[
                        "Plan.B"
                    ]
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":14,
            "fee":0,
            "djId":0,
            "v":101,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":95,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":228623,
            "h":{
                "br":320000,
                "fid":0,
                "size":9147080,
                "vd":0
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3658858,
                "vd":-2
            },
            "alia":[
                "原唱：CNBLUE"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5488266,
                "vd":-2
            },
            "cd":"01",
            "name":"Can't Stop (B组现场版)",
            "id":534541397,
            "privilege":{
                "id":534541397,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12787978,
                    "name":"李让同学"
                },
                {
                    "id":13056451,
                    "name":"靖佩瑶"
                },
                {
                    "id":13059432,
                    "name":"董岩磊"
                }
            ],
            "al":{
                "id":37579301,
                "name":"偶像练习生 表演曲目合集",
                "picUrl":"https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg",
                "pic_str":"109951163170276615",
                "pic":109951163170276600
            },
            "st":0,
            "no":3,
            "fee":0,
            "djId":0,
            "v":86,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":90,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1377826,
            "cf":"",
            "dt":157856,
            "h":{
                "br":320000,
                "fid":0,
                "size":6321676,
                "vd":-22000
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2528697,
                "vd":-18000
            },
            "alia":[
                "原唱：DJ Snake & Lil Jon"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":3793023,
                "vd":-19500
            },
            "cd":"01",
            "name":"Turn Down for What (Live)",
            "id":544000402,
            "privilege":{
                "id":544000402,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":320000,
                "dl":320000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":320000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12274111,
                    "name":"任嘉伦"
                },
                {
                    "id":6076,
                    "name":"俞灏明"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":29817313,
                    "name":"费启鸣"
                }
            ],
            "al":{
                "id":72070002,
                "name":"童话梦想家",
                "picUrl":"https://p2.music.126.net/-kLC8gL27b236EWFM5uVSA==/109951163446549794.jpg",
                "pic_str":"109951163446549794",
                "pic":109951163446549800
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":6,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":90,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1416500,
            "cf":"",
            "dt":190666,
            "h":{
                "br":320000,
                "fid":0,
                "size":7628844,
                "vd":-20900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3051564,
                "vd":-16800
            },
            "alia":[
                "节目《超能幼稚园》片尾曲"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4577324,
                "vd":-18300
            },
            "cd":"1",
            "name":"童话梦想家",
            "id":1299550218,
            "privilege":{
                "id":1299550218,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":4,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12274111,
                    "name":"任嘉伦"
                },
                {
                    "id":6076,
                    "name":"俞灏明"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                },
                {
                    "id":29817313,
                    "name":"费启鸣"
                }
            ],
            "al":{
                "id":72015226,
                "name":"我只是个孩子",
                "picUrl":"https://p2.music.126.net/agkP-pvcGfBT0OWIkJdFmQ==/109951163437872756.jpg",
                "pic_str":"109951163437872756",
                "pic":109951163437872750
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":7,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":85,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":1416500,
            "cf":"",
            "dt":227624,
            "h":{
                "br":320000,
                "fid":0,
                "size":9107374,
                "vd":-19900
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3642976,
                "vd":-15800
            },
            "alia":[
                "节目《超能幼稚园》主题曲"
            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5464442,
                "vd":-17400
            },
            "cd":"1",
            "name":"我只是个孩子",
            "id":1298130518,
            "privilege":{
                "id":1298130518,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":4,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":1142042,
                    "name":"徐梦圆"
                },
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                }
            ],
            "al":{
                "id":36633094,
                "name":"KINGSMAN",
                "picUrl":"https://p2.music.126.net/ldh6m60z5UuxlK5LVnifDw==/109951163046793719.jpg",
                "pic_str":"109951163046793719",
                "pic":109951163046793710
            },
            "st":0,
            "no":0,
            "fee":0,
            "djId":0,
            "v":8,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":80,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":462012,
            "cf":"",
            "dt":228011,
            "h":{
                "br":320000,
                "fid":0,
                "size":9123048,
                "vd":-28599
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3649245,
                "vd":-25200
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5473846,
                "vd":-26199
            },
            "cd":"01",
            "name":"KINGSMAN",
            "id":514054561,
            "privilege":{
                "id":514054561,
                "fee":0,
                "payed":0,
                "st":0,
                "pl":999000,
                "dl":999000,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":999000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                }
            ],
            "al":{
                "id":74210688,
                "name":"Show Me",
                "picUrl":"https://p2.music.126.net/9xoTMqmU6nlqvY6WRhJYbw==/109951163641264944.jpg",
                "pic_str":"109951163641264944",
                "pic":109951163641264940
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":5,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":80,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":201609,
            "h":{
                "br":320000,
                "fid":0,
                "size":8066656,
                "vd":-2
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3226688,
                "vd":-2
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4840011,
                "vd":-2
            },
            "cd":"01",
            "name":"Show Me",
            "id":1322299910,
            "privilege":{
                "id":1322299910,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                },
                {
                    "id":12773144,
                    "name":"韩沐伯"
                }
            ],
            "al":{
                "id":72192132,
                "name":"绯",
                "picUrl":"https://p2.music.126.net/ePFZSPhvpFYTqxGcL0jcLA==/109951163446908880.jpg",
                "pic_str":"109951163446908880",
                "pic":109951163446908880
            },
            "st":1,
            "no":1,
            "fee":8,
            "djId":0,
            "v":10,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":70,
            "rtype":0,
            "rurl":null,
            "rt":null,
            "mst":9,
            "cp":22036,
            "cf":"",
            "dt":166907,
            "h":{
                "br":320000,
                "fid":0,
                "size":6679031,
                "vd":-2
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":2671639,
                "vd":-2
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":4007436,
                "vd":-2
            },
            "cd":"1",
            "name":"绯",
            "id":1299873774,
            "privilege":{
                "id":1299873774,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":256,
                "preSell":false
            }
        },
        {
            "rtUrls":[

            ],
            "ar":[
                {
                    "id":12775210,
                    "name":"秦奋"
                }
            ],
            "al":{
                "id":84388544,
                "name":"红旗飘飘",
                "picUrl":"https://p2.music.126.net/3ro4RFV2FaPnk_p8MBTurw==/109951164582603045.jpg",
                "pic_str":"109951164582603045",
                "pic":109951164582603040
            },
            "st":1,
            "no":0,
            "fee":8,
            "djId":0,
            "v":2,
            "mv":0,
            "pst":0,
            "t":0,
            "pop":70,
            "rtype":0,
            "rurl":null,
            "rt":"",
            "mst":9,
            "cp":1416582,
            "cf":"",
            "dt":247687,
            "h":{
                "br":320000,
                "fid":0,
                "size":9909856,
                "vd":-48071
            },
            "l":{
                "br":128000,
                "fid":0,
                "size":3963968,
                "vd":-43826
            },
            "alia":[

            ],
            "crbt":null,
            "rtUrl":null,
            "ftype":0,
            "a":null,
            "m":{
                "br":192000,
                "fid":0,
                "size":5945931,
                "vd":-45470
            },
            "cd":"01",
            "name":"红旗飘飘",
            "id":1412241777,
            "privilege":{
                "id":1412241777,
                "fee":8,
                "payed":0,
                "st":0,
                "pl":128000,
                "dl":0,
                "sp":7,
                "cp":1,
                "subp":1,
                "cs":false,
                "maxbr":999000,
                "fl":128000,
                "toast":false,
                "flag":64,
                "preSell":false
            }
        }
    ],
    mode: playMode.sequence,// 播放模式
    currentIndex: 0,// 当前歌曲在播放列表的索引位置
    showPlayList: false,// 是否展示播放列表
    currentSong: {} 
});

export default (state = defaultState, action) => {
    switch (action.type) {
        case actionTypes.SET_CURRENT_SONG:
            return state.set ('currentSong', action.data);
        case actionTypes.SET_FULL_SCREEN:
            return state.set ('fullScreen', action.data);
        case actionTypes.SET_PLAYING_STATE:
            return state.set ('playing', action.data);
        case actionTypes.SET_SEQUECE_PLAYLIST:
            return state.set ('sequencePlayList', action.data);
        case actionTypes.SET_PLAYLIST:
            return state.set ('playList', action.data);
        case actionTypes.SET_PLAY_MODE:
            return state.set ('mode', action.data);
        case actionTypes.SET_CURRENT_INDEX:
            return state.set ('currentIndex', action.data);
        case actionTypes.SET_SHOW_PLAYLIST:
            return state.set ('showPlayList', action.data);
        default:
            return state;
    }
}
